language: python
python:
    - "3.7"

install:
    - pip install -r requirements.txt
    - npm install -g sass

script:
    - make clean
    - make build

deploy:
    provider: pages:git
    token: $GITHUB_TOKEN
    edge: true # opt in to dpl v2

    local_dir: _build
    on:
        branch: main